- name: Create chrony configuration
  template:
    src: templates/etc_chrony_conf-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.j2
    dest: "{{ role_bi_time_chrony_location_chrony_conf }}"
    owner: root
    group: root
    mode: '0644'
  notify: chronyd_restart

- name: Enable chrony configuration.
  service:
    name: "{{ role_bi_time_chrony_service }}"
    enabled: yes
