- name: Create chrony configuration
  template:
     src: templates/etc_chrony_conf-CentOS-8.j2
     dest: /etc/chrony.conf
     owner: root
     group: root
     mode: '0644'
  register: role_bi_time_chrony_etc_chrony_conf

- name: Reload chrony configuration.
  service:
     name: "{{ role_bi_time_chrony_service }}"
     state: restarted
  when: role_bi_time_chrony_etc_chrony_conf.changed
